### ISSUE TITLE
Add Campus Map

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#15]

**Comment by ompiepy** [comment]
@nikhanal yesko PR ma change garenau pahilo ko ma changes haru suggestions haru incorporate gara na

**Comment by nikhanal** [comment]
@ompiepy maile aba next pr ma incorporate garera pathauxu hai

**Comment by ompiepy** [comment]
Commit and PR often gareko ramro ho nishan tara yekai choti garda ni huncha. Good practice is to Commit and send PR often.

**Comment by nikhanal** [comment]
huss om i will follow it

**Comment by ompiepy** [comment]
How about adding the Campus Map under the quick Links in the Footer rather than in about section

**Comment by ompiepy** [comment]
Campus Map -place this in footer (https://tcioe.edu.np/about/map) currently being placed at the about section.

**Comment by nikhanal** [comment]
Sure

**Comment by ompiepy** [comment]
Thanks for the update
