### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#159]
PDF should be embedded within the website, Currently we have to click to open in next tab
Design was ready.

**Comment by khemrajshrestha471** [comment]
Let me do this @ompiepy ...

**Comment by ompiepy** [comment]
Thanks, @khemrajshrestha471 .

**Comment by khemrajshrestha471** [comment]
@ompiepy where can we find the design for that?

**Comment by ompiepy** [comment]
@bikrantbdr You worked on this before right? Can you help Khemraj.

**Comment by bikrantbdr** [comment]
I had already made the page,
the iframe embedding was a problem so i had to redirect the pdf to a new tab temporarily, we can solve the issue if we can figureout why iframe component was not working properly

**Comment by ompiepy** [comment]
We need to figure out that problem.

**Comment by ompiepy** [comment]
PR #176 solves the embedding. Thanks, @khemrajshrestha471 and @bikrantbdr . Closing this.

**Comment by ompiepy** [comment]
PR #179 #180 #181 #182 #183 Solves this for PC. @khemrajshrestha471 Keep working the better solution for the mobile view. We will starting using this code to view in other places too. Thank you.

**Comment by ompiepy** [comment]
PR #194 #195 #196 Solves this for mobile view. Thanks @khemrajshrestha471. A special thank you to our friend, [Niyoj Oli](https://github.com/niyoj/) for working on the PDF Viewer Component,
