### ISSUE TITLE
Key Campus Officials

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#16]

**Comment by nikhanal** [comment]
I will resolve this issue provide me with api with needed datas

**Comment by ompiepy** [comment]
@Strange18 and @bibek could you please put the database and api rquired.

**Comment by ompiepy** [comment]
for Key Campus Officials -> https://tcioe.edu.np/about/keyofficials

**Comment by ompiepy** [comment]
Key Campus Officials page is not working.

**Comment by nikhanal** [comment]
sure I will work on it

**Comment by ompiepy** [comment]
Thanks, nishan. Please, try making this flexible so that we can reuse this part to other places as well. like in the units and sections officials hierarchy and departs hierarchy

**Comment by ompiepy** [comment]
BUG: Takes forever to load on adding the new data.
![image](https://github.com/Strange18/tcioe-node/assets/66164291/84c7a164-09d9-4f22-89b4-5eddd14870ef)

**Comment by ompiepy** [comment]
This is resolved for now, will do the same in Sections and Units.
