### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#161]
Controllable in Backend - Done
Upload file from Backend - Done
remove quality assurance and audit report tab (1st and 4th one) from this fig.
![image](https://github.com/Strange18/tcioe-node/assets/66164291/3b586664-936e-4d76-8799-86dcd7cd7373)
Add Other Reports at the end.

Data endpoints are available at https://notices.tcioe.edu.np/api/report/ for all the Sub web pages under Resources.
UI should be similar to as of https://tcioe.edu.np/notices/7a926935-2e3f-4b55-a8a8-b59e10e8fb9e (Note: Reuse embedded code)

**Comment by ompiepy** [comment]
@jyotsna-jha Will you solve this issue? I will explain the details what needs to be done.

**Comment by ompiepy** [comment]
Thanks, @jyotsna-jha  . I will assign this. The informatiosn are available here too. Please, ping me at vc at your convenience so that I can explain in more detail.

**Comment by jyotsna-jha** [comment]
Thank you so much @ompiepy

**Comment by ompiepy** [comment]
alumni page

**Comment by ompiepy** [comment]
Closing for now. I have some few ideas to change. Thank @jyotsna-jha  for the assist. PR #193 #192 solves this.

**Comment by ompiepy** [comment]
PR #213 solves this. Thank you @jyotsna-jha .
