### ISSUE TITLE
Campus Life -> Unions

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#162]
Add image of the unions team hierarchy -> This should be scalable.
Make page of FSU similar to other unions (Done)

**Comment by jyotsna-jha** [comment]
I will do this

**Comment by ompiepy** [comment]
Thanks, Jyotsana for solving a task of this issue. PR #170

**Comment by ompiepy** [comment]
Closing this issue, with note "May require to add the picture of the team executive". Thanks, @jyotsna-jha for your contribution.
