### ISSUE TITLE
Remove TCIOE from homepage

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#163]
![image](https://github.com/Strange18/tcioe-node/assets/66164291/40fc0890-160b-4446-8f2b-3fbbf732654c)

**Comment by jyotsna-jha** [comment]
I will do this

**Comment by ompiepy** [comment]
Thanks, jyotsana.

**Comment by ompiepy** [comment]
PR #166 fixes this. Thank @jyotsna-jha. Closing this issue.
