### ISSUE TITLE
Updated Organization Chart

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#17]
ganesh sir has updated one

**Comment by ompiepy** [comment]
@itsanmol124 please, prepare the organization chart from the reference given to you.

**Comment by itsanmol124** [comment]
ok

**Comment by ompiepy** [comment]
for Organization Chart -> https://tcioe.edu.np/about/organization

**Comment by ompiepy** [comment]
@jyotsna-jha Will you work on this?

**Comment by jyotsna-jha** [comment]
Sure @ompiepy
