### ISSUE TITLE
Code of Conduct Sections

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#18]
https://tcioe.edu.np/resources/studentcoc
- yesko content chahi ioe bulletin bata line (points 14 and 15) yo pani website mai rakhne content, pdf bata hoina 
[ioe bulletin.pdf](https://github.com/Strange18/tcioe-node/files/12065707/ioe.bulletin.pdf)
(No data)

https://tcioe.edu.np/resources/professionalcoc
- Content to be taken from here(https://www.nec.gov.np/uploads/brochure/vqWyQ2eizB170618111120.pdf). yo chahi website nai dekhine banau hai not pdf.
- (Done)

**Comment by ompiepy** [comment]
@khemrajshrestha471 Will you work on this?

**Comment by ompiepy** [comment]
https://tcioe.edu.np/resources/tuact
for this template similar to https://tcioe.edu.np/resources/calendar/be. There will be 5 heading and pdf will be polutaled into each one. Tha database will contain those pdfs.

**Comment by khemrajshrestha471** [comment]
lemee do this too
