### ISSUE TITLE
End Point providing data of key campus officials

### ISSUE THREAD

**Issue by nikhanal** [Strange18/tcioe-node#21]

**Comment by ompiepy** [comment]
Is this resolved @nikhanal ?

**Comment by whoisdinanath** [comment]
This was already provided at the staff members endpoint.
A boolean value is_key_official distinguishes the key officials with other staff members

**Comment by nikhanal** [comment]
@whoisdinanath 
data hierarchy ma xaina tyo milaideuna hai. Serial wise haldeuna rank anusar.

**Comment by whoisdinanath** [comment]
@nikhanal changes has been made, will be reflected in the next sprint.

**Comment by ompiepy** [comment]
@nikhanal Did you get all the information. Can I close this issue?

**Comment by nikhanal** [comment]
@ompiepy data consistent xaina ani heirarchy pani thik xaina parsi suman sir sanga basera garnu parxa hola

**Comment by Strange18** [comment]
@nikhanal  ma kam gardai xu

**Comment by nikhanal** [comment]
thank you @whoisdinanath and @Strange18  for providing required data 
@ompiepy this issue has been resolved you may close it
