### ISSUE TITLE
Add Year in Notices Tab

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#4]
![image](https://github.com/Strange18/tcioe-node/assets/66164291/3a3eaca2-5f33-4bb4-9738-76aa90b8e058)
This should show the year also

**Comment by ompiepy** [comment]
@bikrantbdr dai are you still working on this?

**Comment by bikrantbdr** [comment]
I was focusing on Major project for the last few days,
I will catch up with you guys.

and regarding that date, i don't think adding year to that would be good
for UI. Maybe adding the full date in particular notice page is better
[image: image.png]

**Comment by ompiepy** [comment]
Thank you so much for the feedback dai.

**Comment by ompiepy** [comment]
pagination and 10 notice per page #31 closes this too.
