### ISSUE TITLE
Phone Directory

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#44]
![image](https://github.com/Strange18/tcioe-node/assets/66164291/68fb20cc-301b-43d4-be19-f0a88924fc58)
yesko content rakhera yeuta page banau parcha
plus How about adding this do the Quick Links in the footer section of the homepage

**Comment by ompiepy** [comment]
ask suman dai

**Comment by ompiepy** [comment]
@Prateek61 Will you work on this?

**Comment by Prateek61** [comment]
> Collaborator



> @Prateek61 Will you work on this?

i will work on this
