### ISSUE TITLE
Work in progress Page

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#45]
Forward the following links to the Work in Progress Page similar to this: 
![image](https://github.com/Strange18/tcioe-node/assets/66164291/4c48c94b-ad72-4607-839f-d14e144627cb)
LIST GOES HERE
1. My Portal

**Comment by ompiepy** [comment]
@khemrajshrestha471 Will you work on this?

**Comment by ompiepy** [comment]
@jyotsna-jha Will you please work on this?

**Comment by jyotsna-jha** [comment]
@ompiepy yess I will do this

**Comment by ompiepy** [comment]
Thanks @jyotsna-jha for the template. I have complted this closing this issue.
