### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#5]
1. Thesis -> DSpace
2. Add Check Mail(https://mail.google.com) in the Sub Menu bar beside My Portal

**Comment by ompiepy** [comment]
@nikhanal Check mail should open the link in next window, please check.

**Comment by ompiepy** [comment]
@nikhanal Please, solve this issue.

**Comment by nikhanal** [comment]
sure

**Comment by nikhanal** [comment]
@ompiepy it's resolved. I will create pr once i complete about page

**Comment by ompiepy** [comment]
Thanks, I will merge this.
