### ISSUE TITLE
Redesign Journal Page

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#50]
1. Change the Editorial Board and Contents of existing page (All Contents should be takeen from https://www.nepjol.info/index.php/jiee/index) 
2. Make the deign modern ([jounal.tcioe.edu.np](https://journal.tcioe.edu.np/)) -> Take inspiration from https://www.sciencedirect.com/journal/renewable-and-sustainable-energy-reviews  - Done (We have Figma Design)

**Comment by ompiepy** [comment]
The Journal Publications from the resource sections should be removed from there.

**Comment by ompiepy** [comment]
@Sudeep-K Will you work on this?

**Comment by ompiepy** [comment]
need UI @itsanmol124

**Comment by ompiepy** [comment]
Requirements of Journal Page:
1. Article
2. Submit your article (Link)
3. Guide for Authors (We have doc)

**Comment by ompiepy** [comment]
@itsanmol124 May I assign you for the UI?

**Comment by itsanmol124** [comment]
Ok

**Comment by ompiepy** [comment]
Thank you so much, Anmol. Please, feel free to reach out in case of any problem. You can find details on what to include here in the repo iteself too.

**Comment by itsanmol124** [comment]
Design Link: https://www.figma.com/file/3fLq8WTvVAp4wntpifDiDW/Website-TCIOE?type=design&node-id=602-460&mode=design

**Comment by ompiepy** [comment]
Thanks, @khemrajshrestha471. Please, let us know if you have any doubts.

**Comment by ompiepy** [comment]
3 distinct pages
1. Editorial Board
2. Aims and Scope
3. Article Viewing

**Comment by ompiepy** [comment]
Design for the Editorial Board
Informations
Photo
Role= Editor-in-Chief
Name = Khem Gyanwali, PhD
Designation=Assistant Professor
Department=Department of Automobile and Mechanical Engineering
Organization=Thapathali Campus , Tribhuvan University, Nepal
Email: [gyanwalikhem@ioe.edu.np](mailto:gyanwalikhem@ioe.edu.np)

**Comment by itsanmol124** [comment]
Editorial Board Page Design: https://www.figma.com/file/3fLq8WTvVAp4wntpifDiDW/Website-TCIOE?type=design&node-id=602-460&mode=design
@khemrajshrestha471

**Comment by khemrajshrestha471** [comment]
thank you @itsanmol124

**Comment by ompiepy** [comment]
Thank you @khemrajshrestha471 , @itsanmol124 and @Prateek61 . Closing this.
