### ISSUE TITLE
Open in New Tab

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#52]
Under Admssion:
1. BE-Barch admission -> open in next tab
2. master's admission -> open in next tab

**Comment by ompiepy** [comment]
Facebook Link of home page clickable in next page

**Comment by ompiepy** [comment]
@jyotsna-jha Will you work on this?

**Comment by jyotsna-jha** [comment]
okay I will do that @ompiepy

**Comment by ompiepy** [comment]
Thanks @jyotsna-jha , I will close this issue for now.
