### ISSUE TITLE
Rectify Student Testimonials

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#55]

**Comment by ompiepy** [comment]
@Prateek61 Will you recify this to provide the actual testimonials @whoisdinanath can you provide the testimonials provided by UKG sor?

**Comment by whoisdinanath** [comment]
@ompiepy All the files provided by sir is uploaded in recourses channel already!

**Comment by Prateek61** [comment]
> @Prateek61 Will you recify this to provide the actual testimonials @whoisdinanath can you provide the testimonials provided by UKG sor?

i will look into it

**Comment by ompiepy** [comment]
Scrolling issue in the Testimonials

**Comment by ompiepy** [comment]
Thanks @Prateek61
