### ISSUE TITLE
Changes images to our own images in different places

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#7]
Assign suman dai

**Comment by ompiepy** [comment]
I have requested shanta sir for this.

**Comment by ompiepy** [comment]
1. Homepage Photo Change (The first one)
2.  Change photos in the page of our departments.
3.

**Comment by ompiepy** [comment]
@jyotsna-jha Will you please do this?

**Comment by jyotsna-jha** [comment]
Yes I will do this

**Comment by ompiepy** [comment]
I have completed this, closing now.
