### ISSUE TITLE
Add campus clubs

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#85]
Add a page in similar template to these Student Clubs (Content from annual page) sites too.
- AMESIN -Done
- ASIS -Done
- CESS -Done
ECAST - Done
RAC - Done
- SOIES - Done
- Tensor -Done

Remove FITT from Students Clubs - Done

**Comment by ompiepy** [comment]
@jyotsna-jha will you work on this?

**Comment by ompiepy** [comment]
@jyotsna-jha Please, share you status.

**Comment by Shakshi-03** [comment]
@ompiepy  sure

**Comment by jyotsna-jha** [comment]
@ompiepy  yess I will

**Comment by ompiepy** [comment]
Thanks @jyotsna-jha . Closing the issue.
