### ISSUE TITLE
Fee Structure and Scholarship Quota

### ISSUE THREAD

**Issue by ompiepy** [Strange18/tcioe-node#9]
Ask Exam Section for content and add into 
1. Fee Structure -> https://tcioe.edu.np/admissions/fee
2. Scholarship Quota -> https://tcioe.edu.np/admissions/scholarship

**Comment by ompiepy** [comment]
@Prateek61 Will you work in this?

**Comment by Prateek61** [comment]
ok

**Comment by Prateek61** [comment]
> @Prateek61 Will you work in this?

ok

**Comment by ompiepy** [comment]
Fee -> IOE Buletin (Point Number 9)
Annual Intake -> Point Number 2.7
Scholarship Scemes -> 6.1 to 6.5
Add Link to IOE Bulletin too

**Comment by Prateek61** [comment]
> @Prateek61 Do you want to do this, as you have done this before.

sure

**Comment by ompiepy** [comment]
Thanks, @Prateek61 . I will assign this. I have also added the info on what to change. Ping me at vc so that I can explain in detail.
